## Karunya paliwal
## c3-c1-14
## lab3

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [ ]:
df = pd.read_csv("enjoy.csv")

In [ ]:
df.head()

     Sky AirTemp Humidity    Wind Water Forecast EnjoySport
0  Sunny    Warm   Normal  Strong  Warm     Same        Yes
1  Sunny    Warm     High  Strong  Warm     Same        Yes
2  Rainy    Cold     High  Strong  Warm   Change         No
3  Sunny    Warm     High  Strong  Cool   Change        Yes
4  Sunny    Cold   Normal    Weak  Warm     Same         No

In [ ]:
df.tail()

      Sky AirTemp Humidity    Wind Water Forecast EnjoySport
5  Cloudy    Warm   Normal    Weak  Warm     Same         No
6   Sunny    Warm   Normal    Weak  Cool     Same        Yes
7   Rainy    Warm     High    Weak  Cool   Change         No
8   Sunny    Warm   Normal  Strong  Cool     Same        Yes
9   Sunny    Warm     High    Weak  Warm     Same        Yes

In [ ]:
df.describe()

          Sky AirTemp Humidity    Wind Water Forecast EnjoySport
count      10      10       10      10    10       10         10
unique      3       2        2       2     2        2          2
top     Sunny    Warm   Normal  Strong  Warm     Same        Yes
freq        7       8        5       5     6        7          6

In [ ]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
## first : belongs to row second : belongs to column -1 means except enjoy sport

## Find s algorithm

In [ ]:
def find_s(X,y):
  hypothesis=None
  print("initial hypothesis:",hypothesis)
  for i in range (len(X)):
    if y[i]=="Yes":
      if hypothesis is None:
        hypothesis=X[i].copy()
      else:
        for j in range(len(hypothesis)):
          if hypothesis[j]!=X[i][j]:
            hypothesis[j]="?"
    print(f"\nAfter training example{i+1}")
    print(hypothesis)
 return hypothesis
final_hypothesis=find_s(X,y)
print("\nFinal hypothesis")

initial hypothesis: None

After training example1
['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']

After training example2
['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']

After training example3
['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']

After training example4
['Sunny' 'Warm' '?' 'Strong' '?' '?']

After training example5
['Sunny' 'Warm' '?' 'Strong' '?' '?']

After training example6
['Sunny' 'Warm' '?' 'Strong' '?' '?']

After training example7
['Sunny' 'Warm' '?' '?' '?' '?']

After training example8
['Sunny' 'Warm' '?' '?' '?' '?']

After training example9
['Sunny' 'Warm' '?' '?' '?' '?']

After training example10
['Sunny' 'Warm' '?' '?' '?' '?']

Final hypothesis

Candidate elimination algorithm

In [ ]:
from types import GenericAlias
import copy
def candidate_elimination(concepts,target):
  speific=concepts[0].copy()
  general=[["?"for i in range(len(speific))]]
  print("\nInitial S:",speific)
  print("Initial G:",general)
  for i , h in enumerate(concepts):
    if target[i]=="Yes":
      for x in range(len(speific)):
        if h[x]!=speific[x]:
          speific[x]="?"
    else:

      for g_idx in range(len(general) - 1, -1, -1):
          g = general[g_idx]
          if all(s == '?' or s == h[j] for j, s in enumerate(g)):

              if all(h[j] == '?' or h[j] == g[j] for j in range(len(h))):
                  general.pop(g_idx)


      for x in range(len(speific)):
        if h[x]!=speific[x]:
          new_general_hyp = ["?" if j!=x else speific[x]for j in range (len(speific))]
          if new_general_hyp not in general:
              general.append(new_general_hyp)

    print("\nExample",i+1)
    print("S=",speific)
    print("G=",general)
  return speific ,general
S,G=candidate_elimination(X,y)
print("\nFinal S:",S)
print("Final G:",G)
for g in G:
  print(g)

Initial S: ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
Initial G: [['?', '?', '?', '?', '?', '?']]

Example 1
S= ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
G= [['?', '?', '?', '?', '?', '?']]

Example 2
S= ['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']
G= [['?', '?', '?', '?', '?', '?']]

Example 3
S= ['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']
G= [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same']]

Example 4
S= ['Sunny' 'Warm' '?' 'Strong' '?' '?']
G= [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same']]

Example 5
S= ['Sunny' 'Warm' '?' 'Strong' '?' '?']
G= [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', '?', '?', 'Strong', '?', '?']]

Example 6
S= ['Sunny' 'Warm' '?' 'Strong' '?' '?']
G= [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', '?', '?', 'Strong', '?', '?']]

Example 7
S= ['Sunny' 'Warm' '?' '?' '?' '?']
G= [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', '?', '?', 'Strong', '?', '?']]

Example 8
S= ['Sunny' 'Warm' '?' '?' '?' '?']
G= [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', '?', '?', 'Strong', '?', '?']]

Example 9
S= ['Sunny' 'Warm' '?' '?' '?' '?']
G= [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', '?', '?', 'Strong', '?', '?']]

Example 10
S= ['Sunny' 'Warm' '?' '?' '?' '?']
G= [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', '?', '?', 'Strong', '?', '?']]

Final S: ['Sunny' 'Warm' '?' '?' '?' '?']
Final G: [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', '?', '?', 'Strong', '?', '?']]
['?', '?', '?', '?', '?', '?']
['Sunny', '?', '?', '?', '?', '?']
['?', 'Warm', '?', '?', '?', '?']
['?', '?', '?', '?', '?', 'Same']
['?', '?', '?', 'Strong', '?', '?']